"""Generate the frontend wire type from the public Pydantic Agent Run schema."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

BACKEND_ROOT = Path(__file__).resolve().parents[1]
REPO_ROOT = BACKEND_ROOT.parent
OUTPUT = REPO_ROOT / "frontend" / "lib" / "generated" / "agent-run-protocol.ts"

sys.path.insert(0, str(BACKEND_ROOT))

from app.schemas.agent_run import AgentTraceEvent  # noqa: E402


def _typescript_type(schema: dict[str, Any], definitions: dict[str, Any]) -> str:
    if "$ref" in schema:
        name = str(schema["$ref"]).rsplit("/", 1)[-1]
        return _typescript_type(definitions.get(name, {}), definitions)
    if "enum" in schema:
        return " | ".join(json.dumps(item, ensure_ascii=False) for item in schema["enum"])
    if "const" in schema:
        return json.dumps(schema["const"], ensure_ascii=False)
    if "anyOf" in schema:
        choices = [_typescript_type(item, definitions) for item in schema["anyOf"]]
        return " | ".join(dict.fromkeys(choices))
    kind = schema.get("type")
    if kind == "string":
        return "string"
    if kind in {"integer", "number"}:
        return "number"
    if kind == "boolean":
        return "boolean"
    if kind == "null":
        return "null"
    if kind == "array":
        return f"Array<{_typescript_type(schema.get('items', {}), definitions)}>"
    if kind == "object":
        return "Record<string, unknown>"
    return "unknown"


def render() -> str:
    schema = AgentTraceEvent.model_json_schema()
    definitions = schema.get("$defs", {})
    required = set(schema.get("required", []))
    lines = [
        "/* This file is generated by backend/scripts/export_agent_protocol.py. */",
        "/* Do not edit by hand; change backend/app/schemas/agent_run.py instead. */",
        "",
        'export const AGENT_TRACE_SCHEMA_VERSION = "2.0" as const;',
        "",
        "export interface AgentTraceProtocolV2 {",
    ]
    for name, field_schema in schema.get("properties", {}).items():
        optional = "" if name in required else "?"
        lines.append(
            f"  {name}{optional}: {_typescript_type(field_schema, definitions)};"
        )
    lines.extend([
        "  [key: string]: unknown;",
        "}",
        "",
    ])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if the committed frontend type is out of date.",
    )
    args = parser.parse_args()
    generated = render()
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != generated:
            print(f"{OUTPUT} is stale; run {Path(__file__).name}", file=sys.stderr)
            return 1
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(generated, encoding="utf-8")
    print(OUTPUT)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
